set PYTHONIOENCODING=UTF-8   (no efect)  
set PYTHONUTF8=1

In [1]:
import pandas as pd
import numpy as np
import locale
#import sys
import platform 
import os
plt = platform.system()
if plt == "Windows":
    os.environ["PYTHONUTF8"] = "1"
platform.system()

'Windows'

In [2]:
#sys.stdin.reconfigure(encoding='utf-8')
# sys.setdefaultencoding() does not exist, here!
#reload(sys)  # Reload does the trick!
#sys.setdefaultencoding('UTF8')
locale.getpreferredencoding()

'cp1252'

In [3]:
data = {
    "a": [11, 22, 33],
    "b": np.array([11, 22, 33]),
    "c": 3
}
data2 = {
    "a": np.array([111, 22]),
    "b": 2,
    "c": 3,
    "d": [1,2]
}

In [4]:
df = pd.DataFrame(data=data2, index=["one", "two"])
df

       a  b  c  d
one  111  2  3  1
two   22  2  3  2

In [5]:
result = {
    'pli_lt_uty': np.array([0.91584452, 0.97024382]), 
    'pli_mpt_uty': np.array([0.24813473, 0.79757025]), 
    'pli_cont_res_uty': np.array([0.28203083, 0.90652122]), 
    'pli_cont_uty': np.array([0.91584452, 0.97024382]),
    'aa': [1, 2]
}

In [6]:
df = pd.DataFrame(data=result, index=["one", "two"])
df

     pli_lt_uty  pli_mpt_uty  pli_cont_res_uty  pli_cont_uty  aa
one    0.915845     0.248135          0.282031      0.915845   1
two    0.970244     0.797570          0.906521      0.970244   2

In [7]:
pd.__version__

'2.2.3'